### ISSUE TITLE
Ligatures in Terminal work with Monoid, not with Hasklig

### ISSUE THREAD

**Issue by Swissnetizen** [i-tu/Hasklig#18]
I'm seeing a strange issue, ligatures work with [Monoid](https://github.com/larsenwork/monoid) but not with Hasklig in the OS X terminal. See screenshot:
<img width="873" alt="screen shot 2015-07-27 at 18 03 27" src="https://cloud.githubusercontent.com/assets/2052887/8910941/db382d7e-3489-11e5-954a-a3b35a6eb647.png">

**Comment by elucash** [comment]
+1
Same with Eclipse

**Comment by i-tu** [comment]
This is very interesting! It seems Monoid [is using the OpenType Contextual Alternates feature](https://github.com/larsenwork/monoid/blob/master/Utilities/Monoid-*.fea#L69) in a clever/hackish way instead of the Ligatures feature used by Hasklig. This could be the reason for this behaviour.

**Comment by stephencelis** [comment]
FWIW, FiraCode (https://github.com/tonsky/FiraCode) also supports the macOS Terminal.

**Comment by i-tu** [comment]
This issue is fixed in release 1.0 and later

**Comment by jmn** [comment]
Is this fixed? The README still claims no support in OS X Terminal AFAICT.

**Comment by rafaelrinaldi** [comment]
Still doesn't work on Terminal.app. Tested in version 1.1 today.

**Comment by whiteinge** [comment]
Maybe worth double-checking versions and options? 1.1 is working for me in both Terminal.app and iTerm2 (High Sierra):

<img width="1159" alt="screen shot 2018-01-31 at 5 14 14 pm" src="https://user-images.githubusercontent.com/91293/35654455-685e47d4-06aa-11e8-968e-1f4a82d426da.png">

**Comment by rafaelrinaldi** [comment]
I don't see this option. These are the only ones I see:

<img width="294" alt="screen shot 2018-01-31 at 9 22 48 pm" src="https://user-images.githubusercontent.com/87162/35657919-ef5ea7ac-06cc-11e8-8a1c-ff3c7eb1ddf4.png">

Tried checking the ligatures options you see up on the top but without any effects.

**Comment by rafaelrinaldi** [comment]
Oh for some reason I think I still had the old version because that's the only options I was seeing:

<img width="294" alt="screen shot 2018-01-31 at 9 22 48 pm" src="https://user-images.githubusercontent.com/87162/35657987-4c53b2cc-06cd-11e8-8e0d-65b6761dad3c.png">

Removed and installed it again and works like a charm now. Thank you!
